# Database credentials
database:
  user: "postgres"
  name: "db"
  host: "localhost"
  port: "5432"
  password: "myPassword"

# bigtable:
#   project: cleo_explorer
#   instance: cleo_beaconchain_bigtable

# Chain network configuration
chain:
  configPath: ./config/custom.chain.yml
  genesisTimestamp: 1694403000  
  slotsPerEpoch: 32
  secondsPerSlot: 12
  minGenesisActiveValidatorCount: 3
  genesisValidatorsRoot: 0x09ec7348e14d37a735a8a7e12182673c6a5fedaf83d4ac0e785f5816b46c6fab
# Note: It is possible to run either the frontend or the indexer or both at the same time
# Frontend config
frontend:
  enabled: true # Enable or disable to web frontend
  imprint: "./templates/imprint.html"  # Path to the imprint page content
  siteName: "Cleo Explorer" # Name of the site, displayed in the title tag
  siteSubtitle: "Cleo explorer" # Subtitle shown on the main page
  csrfAuthKey: '0123456789abcdef000000000000000000000000000000000000000000000000'
  jwtSigningSecret: "0123456789abcdef000000000000000000000000000000000000000000000000"
  jwtIssuer: "localblockexplorer"
  jwtValidityInMinutes: 30
  server:
    host: "0.0.0.0" # Address to listen on
    port: "3333" # Port to listen on
  database:
    user: "postgres"
    name: "db"
    host: "localhost"
    port: "5432"
    password: "myPassword"
  # sessionSecret: "<sessionSecret>"
  # flashSecret: "" # Encryption secret for flash cookies
# Indexer config
indexer:
  enabled: true # Enable or disable the indexing service
  fullIndexOnStartup: true # Perform a one time full db index on startup
  indexMissingEpochsOnStartup: true # Check for missing epochs and export them after startup
  node:
    host: "localhost" # Address of the backend node
    port: "9596" # GRPC port of the Prysm node
    type: "lodestar" # can be either prysm or lighthouse
    pageSize: 100 # the amount of entries to fetch per paged rpc call, TODO set to 500
  eth1Endpoint: 'http://localhost:8545'
  # Note: 0 is correct, but due to an underflow bug (being fixed), doesn't work.
  eth1DepositContractFirstBlock: 0